#!/bin/sh

xcursorgen all-scroll.in ../../../../Noir\ White/cursors/all-scroll
xcursorgen bottom_tee.in ../../../../Noir\ White/cursors/bottom_tee
xcursorgen cell.in ../../../../Noir\ White/cursors/cell
xcursorgen center_ptr.in ../../../../Noir\ White/cursors/center_ptr
xcursorgen circle.in ../../../../Noir\ White/cursors/circle
xcursorgen color_picker.in ../../../../Noir\ White/cursors/color_picker
xcursorgen col-resize.in ../../../../Noir\ White/cursors/col-resize
xcursorgen context-menu.in ../../../../Noir\ White/cursors/context-menu
xcursorgen copy.in ../../../../Noir\ White/cursors/copy
xcursorgen cross.in ../../../../Noir\ White/cursors/cross
xcursorgen crossed_circle.in ../../../../Noir\ White/cursors/crossed_circle
xcursorgen crosshair.in ../../../../Noir\ White/cursors/crosshair
xcursorgen dnd-ask.in ../../../../Noir\ White/cursors/dnd-ask
xcursorgen dnd-copy.in ../../../../Noir\ White/cursors/dnd-copy
xcursorgen dnd-link.in ../../../../Noir\ White/cursors/dnd-link
xcursorgen dnd-move.in ../../../../Noir\ White/cursors/dnd-move
xcursorgen dnd-no-drop.in ../../../../Noir\ White/cursors/dnd-no-drop
xcursorgen dotbox.in ../../../../Noir\ White/cursors/dotbox
xcursorgen e-resize.in ../../../../Noir\ White/cursors/e-resize
xcursorgen ew-resize.in ../../../../Noir\ White/cursors/ew-resize
xcursorgen grabbing.in ../../../../Noir\ White/cursors/grabbing
xcursorgen hand1.in ../../../../Noir\ White/cursors/hand1
xcursorgen hand2.in ../../../../Noir\ White/cursors/hand2
xcursorgen left_ptr.in ../../../../Noir\ White/cursors/left_ptr
xcursorgen left_ptr_watch.in ../../../../Noir\ White/cursors/left_ptr_watch
xcursorgen left_tee.in ../../../../Noir\ White/cursors/left_tee
xcursorgen link.in ../../../../Noir\ White/cursors/link
xcursorgen ll_angle.in ../../../../Noir\ White/cursors/ll_angle
xcursorgen lr_angle.in ../../../../Noir\ White/cursors/lr_angle
xcursorgen move.in ../../../../Noir\ White/cursors/move
xcursorgen ne-resize.in ../../../../Noir\ White/cursors/ne-resize
xcursorgen nesw-resize.in ../../../../Noir\ White/cursors/nesw-resize
xcursorgen n-resize.in ../../../../Noir\ White/cursors/n-resize
xcursorgen ns-resize.in ../../../../Noir\ White/cursors/ns-resize
xcursorgen nw-resize.in ../../../../Noir\ White/cursors/nw-resize
xcursorgen nwse-resize.in ../../../../Noir\ White/cursors/nwse-resize
xcursorgen pencil.in ../../../../Noir\ White/cursors/pencil
xcursorgen pointer-move.in ../../../../Noir\ White/cursors/pointer-move
xcursorgen question_arrow.in ../../../../Noir\ White/cursors/question_arrow
xcursorgen right_ptr.in ../../../../Noir\ White/cursors/right_ptr
xcursorgen right_tee.in ../../../../Noir\ White/cursors/right_tee
xcursorgen row-resize.in ../../../../Noir\ White/cursors/row-resize
xcursorgen sb_down_arrow.in ../../../../Noir\ White/cursors/sb_down_arrow
xcursorgen sb_left_arrow.in ../../../../Noir\ White/cursors/sb_left_arrow
xcursorgen sb_right_arrow.in ../../../../Noir\ White/cursors/sb_right_arrow
xcursorgen sb_up_arrow.in ../../../../Noir\ White/cursors/sb_up_arrow
xcursorgen se-resize.in ../../../../Noir\ White/cursors/se-resize
xcursorgen s-resize.in ../../../../Noir\ White/cursors/s-resize
xcursorgen sw-resize.in ../../../../Noir\ White/cursors/sw-resize
xcursorgen tcross.in ../../../../Noir\ White/cursors/tcross
xcursorgen top_tee.in ../../../../Noir\ White/cursors/top_tee
xcursorgen ul_angle.in ../../../../Noir\ White/cursors/ul_angle
xcursorgen ur_angle.in ../../../../Noir\ White/cursors/ur_angle
xcursorgen vertical-text.in ../../../../Noir\ White/cursors/vertical-text
xcursorgen watch.in ../../../../Noir\ White/cursors/watch
xcursorgen wayland_cursor.in ../../../../Noir\ White/cursors/wayland_cursor
xcursorgen w-resize.in ../../../../Noir\ White/cursors/w-resize
xcursorgen ul_angle.in ../../../../Noir\ White/cursors/X_cursor
xcursorgen xterm.in ../../../../Noir\ White/cursors/xterm
xcursorgen zoom-in.in ../../../../Noir\ White/cursors/zoom-in
xcursorgen zoom-out.in ../../../../Noir\ White/cursors/zoom-out
