#!/bin/sh

xcursorgen all-scroll.in ../../../Noir/cursors/all-scroll
xcursorgen bottom_tee.in ../../../Noir/cursors/bottom_tee
xcursorgen cell.in ../../../Noir/cursors/cell
xcursorgen center_ptr.in ../../../Noir/cursors/center_ptr
xcursorgen circle.in ../../../Noir/cursors/circle
xcursorgen color_picker.in ../../../Noir/cursors/color_picker
xcursorgen col-resize.in ../../../Noir/cursors/col-resize
xcursorgen context-menu.in ../../../Noir/cursors/context-menu
xcursorgen copy.in ../../../Noir/cursors/copy
xcursorgen cross.in ../../../Noir/cursors/cross
xcursorgen crossed_circle.in ../../../Noir/cursors/crossed_circle
xcursorgen crosshair.in ../../../Noir/cursors/crosshair
xcursorgen dnd-ask.in ../../../Noir/cursors/dnd-ask
xcursorgen dnd-copy.in ../../../Noir/cursors/dnd-copy
xcursorgen dnd-link.in ../../../Noir/cursors/dnd-link
xcursorgen dnd-move.in ../../../Noir/cursors/dnd-move
xcursorgen dnd-no-drop.in ../../../Noir/cursors/dnd-no-drop
xcursorgen dotbox.in ../../../Noir/cursors/dotbox
xcursorgen e-resize.in ../../../Noir/cursors/e-resize
xcursorgen ew-resize.in ../../../Noir/cursors/ew-resize
xcursorgen grabbing.in ../../../Noir/cursors/grabbing
xcursorgen hand1.in ../../../Noir/cursors/hand1
xcursorgen hand2.in ../../../Noir/cursors/hand2
xcursorgen left_ptr.in ../../../Noir/cursors/left_ptr
xcursorgen left_ptr_watch.in ../../../Noir/cursors/left_ptr_watch
xcursorgen left_tee.in ../../../Noir/cursors/left_tee
xcursorgen link.in ../../../Noir/cursors/link
xcursorgen ll_angle.in ../../../Noir/cursors/ll_angle
xcursorgen lr_angle.in ../../../Noir/cursors/lr_angle
xcursorgen move.in ../../../Noir/cursors/move
xcursorgen ne-resize.in ../../../Noir/cursors/ne-resize
xcursorgen nesw-resize.in ../../../Noir/cursors/nesw-resize
xcursorgen n-resize.in ../../../Noir/cursors/n-resize
xcursorgen ns-resize.in ../../../Noir/cursors/ns-resize
xcursorgen nw-resize.in ../../../Noir/cursors/nw-resize
xcursorgen nwse-resize.in ../../../Noir/cursors/nwse-resize
xcursorgen pencil.in ../../../Noir/cursors/pencil
xcursorgen pointer-move.in ../../../Noir/cursors/pointer-move
xcursorgen question_arrow.in ../../../Noir/cursors/question_arrow
xcursorgen right_ptr.in ../../../Noir/cursors/right_ptr
xcursorgen right_tee.in ../../../Noir/cursors/right_tee
xcursorgen row-resize.in ../../../Noir/cursors/row-resize
xcursorgen sb_down_arrow.in ../../../Noir/cursors/sb_down_arrow
xcursorgen sb_left_arrow.in ../../../Noir/cursors/sb_left_arrow
xcursorgen sb_right_arrow.in ../../../Noir/cursors/sb_right_arrow
xcursorgen sb_up_arrow.in ../../../Noir/cursors/sb_up_arrow
xcursorgen se-resize.in ../../../Noir/cursors/se-resize
xcursorgen s-resize.in ../../../Noir/cursors/s-resize
xcursorgen sw-resize.in ../../../Noir/cursors/sw-resize
xcursorgen tcross.in ../../../Noir/cursors/tcross
xcursorgen top_tee.in ../../../Noir/cursors/top_tee
xcursorgen ul_angle.in ../../../Noir/cursors/ul_angle
xcursorgen ur_angle.in ../../../Noir/cursors/ur_angle
xcursorgen vertical-text.in ../../../Noir/cursors/vertical-text
xcursorgen watch.in ../../../Noir/cursors/watch
xcursorgen wayland_cursor.in ../../../Noir/cursors/wayland_cursor
xcursorgen w-resize.in ../../../Noir/cursors/w-resize
xcursorgen X_cursor.in ../../../Noir/cursors/X_cursor
xcursorgen xterm.in ../../../Noir/cursors/xterm
xcursorgen zoom-in.in ../../../Noir/cursors/zoom-in
xcursorgen zoom-out.in ../../../Noir/cursors/zoom-out
